config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users
  resources :secrets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/secret.rb
class Secret < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  #
  # has_secure_password
  # validates :password, presence: true, length: { minimum: 6 }
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def index
    @secrets = Secret.all
    render "secrets/secret"
  end

  def new
    @secret = Secret.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    @user.save
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.create(user_params)
      @user.save
      redirect_to @user
    end

    def show
      @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to @user
      else
        render 'edit'
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path
    end

    # Utilisé dans create et update
    private
    def user_params # Définir les attributs en paramètres !!!!
      params.require(:user).permit(:email)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  # Utilisé dans create et update
  private
  def user_params # Définir les attributs en paramètres !!!!
    params.require(:user).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheSecretPage</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/secrets/secret.html.erb
<%= render 'users/header' %>

<br />
<h3>And the answer is : </h3>

<h1>42</h1>
<br />
<br />
<p>Now, who remembers the questions?</p>

app/views/users/_header.html.erb
<header>
  <p class="ele-flex1"><%= image_tag "THP-perso.png", alt: "THP logo", height: 120 %></p>
  <div class="ele-flex1"
    <br />
    <p class="ele-flex2"><%= link_to 'Home', root_path %></p>
    <p class="ele-flex2"><%= link_to 'Sign up', new_user_path %></p>
    <p class="ele-flex2"><%= link_to 'Login', new_user_path %></p>
  </div>
</header>

app/views/users/edit.html.erb
<%= render 'header' %>

<h1>Edit user</h1>

<%= form_with(model: @user, local: true) do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label "Edit user" %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/users/index.hrml.erb
<%= render 'header' %>

<div>
  <h1>The answer to Life, the Universe and Everything?</h1>
  <h3>Read Douglas Adams's books (forget about Dr Who, he is a jerk!)</h3>
  <br />
  <br />
  <p><%= link_to 'Want to know the answer?', secrets_path %></p>
</div>

app/views/users/new.html.erb
<%= render 'header' %>

<br />
<p class="form"><Sign up:></p>
    <%= form_for @user do |f| %>
    <p class="form">Your mail address: <%= f.text_field :email %></p>
    <p class="form">Your password: <%= f.text_field :password_digest %></p>
    <p class="form">Confirm your password: <%= f.text_field :password_digest %></p>
    <p class="formButton"><%= f.submit "Create account" %></p>
  <% end %>

app/views/users/show.html.erb
<%= render 'header' %>

<h2>New user</h2>

<table>
  <tr>
    <th></th>
    <!-- <th>Nom ou Pseudo</th> -->
    <th>New User</th>
  </tr>
  <tr>
    <td><%= @user.email %></td>
  </tr>
</table>